language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable

services: rabbitmq

before_install:
  - export ROOT_PATH=`pwd`

before_script:
  - cargo install cargo-travis --force
  - export PATH=$HOME/.cargo/bin:$PATH;

script:
  - cd $ROOT_PATH/async   && cargo build
  - cd $ROOT_PATH/async   && cargo test
  - cd $ROOT_PATH/futures && cargo build
  - cd $ROOT_PATH/futures && cargo test

after_success:
  - cargo coveralls

dist: trusty
#sudo: false

